#
# Removes primary-cluster resources for each application
#

################################################
#                  PingAccess
################################################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingaccess-admin
$patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-periodic-backup
$patch: delete

---

################################################
#               PingAccess-WAS
################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingaccess-was-admin
$patch: delete

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-was-admin-ingress
$patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-was-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-was-periodic-backup
$patch: delete

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
$patch: delete

---

################################################
#                PingFederate
################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingfederate-admin
$patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingfederate-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-periodic-backup
$patch: delete

---

################################################
#                PingDirectory
################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingdirectory-periodic-backup
$patch: delete

---

################################################
#                MyPing
################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14c-bootstrap
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14c-bom-service
$patch: delete

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14c-oauth-service
$patch: delete

---

apiVersion: batch/v1
kind: Job
metadata:
  name: pingfederate-admin-configurator
$patch: delete