### Deploy the git key of the CD tool to the cluster state repo ###
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-git-deploy
  namespace: argocd
data:
  identity: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF0Z2xSZi81eVZMWGR1MWpJN29WU2pGU1ZHWXBXeFk5NWhTMVhPaUhvTXV0TXhsbGZSSnpBCmR5NEx4RlBWM3oyKzNvYnBzNnR1MzJMTmFIQkk2RXZicWtyaDMzZ1cwSkpYWitVd0xzd2J5amE0SlhiYjFSbVF6NlY2UTgKU2RYYTB0TXo2cS94cjJDb003ZFoyeW1KN1l0S0VZcHJIRVlHZXhZNEdxRG9EdXM5emFuUFR6dHJTMEwvTFZ0NVhQSm5MbwpWdjEycUJrUEhQNTQrWDRqdTN3UUg2TkdjOGN2STRvd3FyZGJyZnlMdnpYaFA4NGtsOTJzSmF3V2ZXa1ExRW8yL1FNWkQrCkl0VWhuVWtiZTg4NlVkY1kwdXJqYmJUUjNYY2kzUFVEUTVibHluMVdiV0RSWHoxUHNHMmYrTkdJU0dSMW1zUTlQdGVhVzYKUjMwRzl3eUJTUUFBQTlBaGdzVEZJWUxFeFFBQUFBZHpjMmd0Y25OaEFBQUJBUUMyQ1ZGLy9uSlV0ZDI3V01qdWhWS01WSgpVWmlsYkZqM21GTFZjNkllZ3k2MHpHV1Y5RW5NQjNMZ3ZFVTlYZlBiN2VodW16cTI3ZllzMW9jRWpvUzl1cVN1SGZlQmJRCmtsZG41VEF1ekJ2S05yZ2xkdHZWR1pEUHBYcER4SjFkclMwelBxci9HdllLZ3p0MW5iS1ludGkwb1JpbXNjUmdaN0ZqZ2EKb09nTzZ6M05xYzlQTzJ0TFF2OHRXM2xjOG1jdWhXL1hhb0dROGMvbmo1ZmlPN2ZCQWZvMFp6eHk4amlqQ3F0MXV0L0l1LwpOZUUvemlTWDNhd2xyQlo5YVJEVVNqYjlBeGtQNGkxU0dkU1J0N3p6cFIxeGpTNnVOdHROSGRkeUxjOVFORGx1WEtmVlp0CllORmZQVSt3YlovNDBZaElaSFdheEQwKzE1cGJwSGZRYjNESUZKQUFBQUF3RUFBUUFBQVFBSHNQTVpsbFdjVUtiU3NKaWsKdzB0T2xKQk1LUFVybWJsSHNEZThSQXg4Z2thWEp0V0luNXJlTGpyZkM2L0FvK281bXJlckdMWXhpQW9udkg3SUdkUnBLSQpyTWwxVlhjS2R5dzFNNjF2TGhvMWc2ZFFBcXk4NjdoMEZZTmFsMGVNbXRIWnU1OVppcHJ3dkhGMmVoWFN6SXpQbXVxVm9qCnZKM1pGM1JvOG5lamI4SWJZaHY3Tms2dENJUXh0aXdRWXJzTlNxUHhSNW03RHMydHNoSldSRG5OTFJ6RzhZaGNrNzNoN2wKMnlpZUZOSWNlZGpxbGJGMU5Ld3MydE54QjdtZ3NBaUs1bEY3bllyMEpLZmJENFh5WTFWdkZ1ZmVjeVRoVkh2eTl3M0hLRwo5dVdIZ0hJOE9FS2trbmd3UFJpazc2WGViaDVqYzRMTHpVSEpsTlVnQVdoVkFBQUFnUUNHR3B2RHRaUjJRSVplazZ5ZG1hClFkVGMrWWxRVjNnWnBsN25KVmw2MjQrKzQvZ0dNRTN4MjVCNnFGZHY3NXdkSnU1Z3MyK2ZSZFpJeXhuc04rdVMxait2RkgKWkFsUVhPb1hPMnNuTzZLRzY5eHNTZ3JySE9kUnY1bEROd3BabXU2dDBuRU05MGlOQTNFbXFraHJ0bCtjR1dNR0xveVYzNQpLWkdsaFFPSEVLRndBQUFJRUE2alE3bkRrME5aMFVzek4xK0ZEUEFPU3BvRXFiaC95N05MdldmSUZWRXhwbW5OcExiK0NiCmZlckxZN2NYRjcwRzlyZUUwYTlVckMvSlJhVTU2MWVrbjRzdktVRGdvMUpMQzl1WHhvN0FKeFVWSmsvRzVKUG1lbDF5anEKK09HbHBRNXRhNktIcUxYcUpId0hZamlpYXNHY1pESlVGOEhDNGM5VldsaGRpNjVBOEFBQUNCQU1iNk9VTUhVa2RaS09oWAp0cVkrM3FuSGFYTVVOOUZsalhBRVc0L2w0RmxBSXc2OHJkUDE2UVFqU09yWVZXMXhmUGdYZUJ6WXdWdzRRZ0JGVFRpbnhmCnlJc1YzQlQ5b0dYTE5KSUJyUWYyVnhpTEg2ZHpRdldDRkh1TlRTOUFYTkFPUXVxTkhBaVdURXc2ay9sNFBwbHhRRk5BbFEKWWNlUEJQaDBtckt3RVEwbkFBQUFHbkp2YzNOcmQyOXVaMEJ3YVc1bmFXUmxiblJwZEhrdVkyOXQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF0Z2xSZi81eVZMWGR1MWpJN29WU2pGU1ZHWXBXeFk5NWhTMVhPaUhvTXV0TXhsbGZSSnpBCmR5NEx4RlBWM3oyKzNvYnBzNnR1MzJMTmFIQkk2RXZicWtyaDMzZ1cwSkpYWitVd0xzd2J5amE0SlhiYjFSbVF6NlY2UTgKU2RYYTB0TXo2cS94cjJDb003ZFoyeW1KN1l0S0VZcHJIRVlHZXhZNEdxRG9EdXM5emFuUFR6dHJTMEwvTFZ0NVhQSm5MbwpWdjEycUJrUEhQNTQrWDRqdTN3UUg2TkdjOGN2STRvd3FyZGJyZnlMdnpYaFA4NGtsOTJzSmF3V2ZXa1ExRW8yL1FNWkQrCkl0VWhuVWtiZTg4NlVkY1kwdXJqYmJUUjNYY2kzUFVEUTVibHluMVdiV0RSWHoxUHNHMmYrTkdJU0dSMW1zUTlQdGVhVzYKUjMwRzl3eUJTUUFBQTlBaGdzVEZJWUxFeFFBQUFBZHpjMmd0Y25OaEFBQUJBUUMyQ1ZGLy9uSlV0ZDI3V01qdWhWS01WSgpVWmlsYkZqM21GTFZjNkllZ3k2MHpHV1Y5RW5NQjNMZ3ZFVTlYZlBiN2VodW16cTI3ZllzMW9jRWpvUzl1cVN1SGZlQmJRCmtsZG41VEF1ekJ2S05yZ2xkdHZWR1pEUHBYcER4SjFkclMwelBxci9HdllLZ3p0MW5iS1ludGkwb1JpbXNjUmdaN0ZqZ2EKb09nTzZ6M05xYzlQTzJ0TFF2OHRXM2xjOG1jdWhXL1hhb0dROGMvbmo1ZmlPN2ZCQWZvMFp6eHk4amlqQ3F0MXV0L0l1LwpOZUUvemlTWDNhd2xyQlo5YVJEVVNqYjlBeGtQNGkxU0dkU1J0N3p6cFIxeGpTNnVOdHROSGRkeUxjOVFORGx1WEtmVlp0CllORmZQVSt3YlovNDBZaElaSFdheEQwKzE1cGJwSGZRYjNESUZKQUFBQUF3RUFBUUFBQVFBSHNQTVpsbFdjVUtiU3NKaWsKdzB0T2xKQk1LUFVybWJsSHNEZThSQXg4Z2thWEp0V0luNXJlTGpyZkM2L0FvK281bXJlckdMWXhpQW9udkg3SUdkUnBLSQpyTWwxVlhjS2R5dzFNNjF2TGhvMWc2ZFFBcXk4NjdoMEZZTmFsMGVNbXRIWnU1OVppcHJ3dkhGMmVoWFN6SXpQbXVxVm9qCnZKM1pGM1JvOG5lamI4SWJZaHY3Tms2dENJUXh0aXdRWXJzTlNxUHhSNW03RHMydHNoSldSRG5OTFJ6RzhZaGNrNzNoN2wKMnlpZUZOSWNlZGpxbGJGMU5Ld3MydE54QjdtZ3NBaUs1bEY3bllyMEpLZmJENFh5WTFWdkZ1ZmVjeVRoVkh2eTl3M0hLRwo5dVdIZ0hJOE9FS2trbmd3UFJpazc2WGViaDVqYzRMTHpVSEpsTlVnQVdoVkFBQUFnUUNHR3B2RHRaUjJRSVplazZ5ZG1hClFkVGMrWWxRVjNnWnBsN25KVmw2MjQrKzQvZ0dNRTN4MjVCNnFGZHY3NXdkSnU1Z3MyK2ZSZFpJeXhuc04rdVMxait2RkgKWkFsUVhPb1hPMnNuTzZLRzY5eHNTZ3JySE9kUnY1bEROd3BabXU2dDBuRU05MGlOQTNFbXFraHJ0bCtjR1dNR0xveVYzNQpLWkdsaFFPSEVLRndBQUFJRUE2alE3bkRrME5aMFVzek4xK0ZEUEFPU3BvRXFiaC95N05MdldmSUZWRXhwbW5OcExiK0NiCmZlckxZN2NYRjcwRzlyZUUwYTlVckMvSlJhVTU2MWVrbjRzdktVRGdvMUpMQzl1WHhvN0FKeFVWSmsvRzVKUG1lbDF5anEKK09HbHBRNXRhNktIcUxYcUpId0hZamlpYXNHY1pESlVGOEhDNGM5VldsaGRpNjVBOEFBQUNCQU1iNk9VTUhVa2RaS09oWAp0cVkrM3FuSGFYTVVOOUZsalhBRVc0L2w0RmxBSXc2OHJkUDE2UVFqU09yWVZXMXhmUGdYZUJ6WXdWdzRRZ0JGVFRpbnhmCnlJc1YzQlQ5b0dYTE5KSUJyUWYyVnhpTEg2ZHpRdldDRkh1TlRTOUFYTkFPUXVxTkhBaVdURXc2ay9sNFBwbHhRRk5BbFEKWWNlUEJQaDBtckt3RVEwbkFBQUFHbkp2YzNOcmQyOXVaMEJ3YVc1bmFXUmxiblJwZEhrdVkyOXQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

---

### Ping app DevOps secret ###

# This should be deleted after populating the secrets for the product licenses
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: devops-secret
data:
  PING_IDENTITY_DEVOPS_USER: cm9zc2t3b25nQHBpbmdpZGVudGl0eS5jb20=
  PING_IDENTITY_DEVOPS_KEY: NmEzYTYyMTctMjI0Yi1kY2U0LTdkMTQtN2JjNjA2YzI4MDRh

---

# NewRelic license key to send APM data
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
data:
  NEW_RELIC_LICENSE_KEY: dW51c2Vk

---
### Licenses ###

# Add PingDirectory.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
type: Opaque

---

# Add pingfederate.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-was-license
type: Opaque

---

### Product passwords ###

# Supported keys:
# Exported as environment variables: PF_ADMIN_USER_PASSWORD, PF_LDAP_PASSWORD, DA_OAUTH_TOKEN_VALIDATOR_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords

---

# Supported keys:
# Mounted as files: root-user-password, admin-user-password, encryption-password, encryption-settings.pin, ads.crt, ads.key
# Exported as environment variables: P14C_ENVIRONMENT_ID, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingdirectory-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
#                                    P14C_ISSUER, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords

---
