kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

# Pingdirectory
# Create the config maps that hold the variable for triggering updates of PD servers
- name: pingdirectory-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingdirectory/env_vars

# Merge all env_vars into Pingdirectory common environment variables configmap
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingdirectory/env_vars


# Pingfederate
# Create the config maps that hold the variable for triggering updates of PF servers
- name: pingfederate-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingfederate/env_vars

# Merge all env_vars into Pingfederate common environment variables configmap
- name: pingfederate-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingfederate/env_vars


# PingAccess
# Create the config maps that hold the variable for triggering updates of PA servers
- name: pingaccess-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess/env_vars

# Merge all env_vars into PingAccess common environment variables configmap
- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess/env_vars


# PingAccess WAS
# Create the config maps that hold the variable for triggering updates of PA WAS servers
- name: pingaccess-was-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess-was/env_vars

# Merge all env_vars into PingAccess WAS common environment variables configmap
- name: pingaccess-was-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess-was/env_vars


# PingDelegator
# Create the config maps that hold the variable for triggering updates of DA servers
- name: pingdelegator-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingdelegator/env_vars

# Ping Delegated Admin
- name: pingdelegator-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingdelegator/env_vars


# PingCloud services
# Pingcloud-metadata
- name: pingcloud-metadata-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars

# PingCloud-oauth
- name: p14c-oauth-service-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

# PingCloud BOM service
- name: p14c-bom-service-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

# PingCloud P14C bootstrap
- name: pingcloud-p14c-bootstrap-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

patchesStrategicMerge:

### Regional enablement - remove admins, backups, etc. from secondary ###
### This patch should be commented out on the primary region ###
# - ../base/ping-cloud/remove-from-secondary-patch.yaml
