---
    startDelaySeconds: 0
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    whitelistObjectNames: ["org.eclipse.jetty.server.handler:type=statisticshandler,*", "org.eclipse.jetty.server:type=connectorstatistics,*", "pingfederate:*"]
    rules:
      - pattern: ".*xx"
      - pattern: ".*TRANSACTIONS_Count"
      - pattern: ".*requestTimeTotal"
      - pattern: ".*requests.*"
      - pattern: ".*connections"
      - pattern: ".*requestTimeMean"    