########################################################################################################################
# This file provides sample patches to update the following settings for each provisioned app:
#
#   - HPA min/max replicas and target CPU utilization
#   - Memory/CPU requests/limits
#   - Disk size
#
# It serves just as a sample and not included from any kustomization.yaml file. PS/GSO must update the
# custom-patches.yaml file using these snippets as appropriate for a customer environment for it to be effective.
########################################################################################################################


################################################
#               Nginx public
################################################

### Update public nginx HPA min/max replicas and target CPU utilization ###
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-public
spec:
  minReplicas: 3
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-ingress-controller
  targetCPUUtilizationPercentage: 70

---

### Update the header size max for customers needing larger sized cookies/headers ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx-public
data:
  large_client_header_buffers: "4 128k"

---

### Update the header size max for customers needing larger sized cookies/headers ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx-public
data:
  large_client_header_buffers: "4 128k"

---

################################################
#              Nginx private
################################################

### Update private nginx HPA min/max replicas and target CPU utilization ###
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx-private
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-ingress-controller
  targetCPUUtilizationPercentage: 70

---

################################################
#                ElasticSearch
################################################

### Update elasticsearch disk size  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elastic-stack-logging
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: elasticsearch-gp2      
      resources:
        requests:
          storage: 40Gi

---

################################################
#                PingDirectory
################################################

### Update pingdirectory disk size  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
  namespace: ping-cloud
spec:
  volumeClaimTemplates:
  - metadata:
      name: out-dir
      labels:
        app: ping-cloud
        role: pingdirectory
        class: pingdirectory-server
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-gp2
      resources:
        requests:
          storage: 40Gi
---

### Update pingdirectory memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
  namespace: ping-cloud
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: pingdirectory
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

################################################
#               PingAccess-WAS
################################################

### Update pingaccess-was-admin disk size  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
  namespace: ping-cloud
spec:
  volumeClaimTemplates:
  - metadata:
      name: out-dir
      labels:
        app: ping-cloud
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingaccess-was-gp2
      resources:
        requests:
          storage: 20Gi

---

### Update pingaccess-was-admin memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was-admin
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

### Update pingaccess-was engine memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

### Update the PingAccess-WAS engine's proxy body size ###
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-was-ingress
  namespace: ping-cloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 16m

---

### Update the PingAccess-WAS engine's proxy body size ###
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-was-ingress
  namespace: ping-cloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 16m

---

### Update pingaccess-was backup cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-was-periodic-backup
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

### Update pingaccess-was admin csd upload cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-was-admin-periodic-csd-upload
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

### Update pingaccess-was engine csd upload cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-was-periodic-csd-upload
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---
################################################
#                PingFederate
################################################

### Update pingfederate-admin disk size  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate-admin
  namespace: ping-cloud
spec:
  volumeClaimTemplates:
  - metadata:
      name: out-dir
      labels:
        app: ping-cloud
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingfederate-gp2
      resources:
        requests:
          storage: 20Gi

---

### Update pingfederate-admin memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate-admin
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingfederate-admin
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

### Update pingfederate engine memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingfederate
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

### Update pingfederate engine HPA min/max replicas and target CPU utilization ###
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingfederate
  namespace: ping-cloud
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pingfederate
  targetCPUUtilizationPercentage: 70

---

### Update pingfederate backup cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-periodic-backup
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

### Update pingfederate admin csd upload cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-admin-periodic-csd-upload
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

### Update pingfederate engine csd upload cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-periodic-csd-upload
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

################################################
#                PingAccess
################################################

### Update pingaccess-admin disk size  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
  namespace: ping-cloud
spec:
  volumeClaimTemplates:
  - metadata:
      name: out-dir
      labels:
        app: ping-cloud
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingaccess-gp2
      resources:
        requests:
          storage: 20Gi

---

### Update pingaccess-admin memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingaccess-admin
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

### Update pingaccess engine memory/cpu requests/limits  ###
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingaccess
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"

---

### Update pingaccess engine HPA min/max replicas and target CPU utilization ###
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess
  namespace: ping-cloud
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pingaccess
  targetCPUUtilizationPercentage: 70

---

### Update pingaccess backup cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-periodic-backup
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

### Update pingaccess admin csd upload cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-admin-periodic-csd-upload
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---

### Update pingaccess engine csd upload cronjob to adjust schedule
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-periodic-csd-upload
  namespace: ping-cloud
spec:
  schedule: "0 * * * *"

---